# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
matrix:
  include:
    - r: 3.2
    - r: 3.3
    - r: 3.4
    - r: 3.5
    - release
    - devel
addons:
  apt:
    packages:
      - devscripts  # For checkbashisms in R 4.0
